# Generated by Django 5.0.2 on 2025-10-17 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_movil_escolar_api', '0003_alumnos_maestros'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maestros',
            old_name='especialidad',
            new_name='área_investigación',
        ),
        migrations.RemoveField(
            model_name='alumnos',
            name='carrera',
        ),
        migrations.RemoveField(
            model_name='alumnos',
            name='matricula',
        ),
        migrations.RemoveField(
            model_name='alumnos',
            name='semestre',
        ),
        migrations.RemoveField(
            model_name='maestros',
            name='titulo',
        ),
        migrations.AddField(
            model_name='alumnos',
            name='clave_alumno',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='alumnos',
            name='curp',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='alumnos',
            name='ocupacion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='alumnos',
            name='rfc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='maestros',
            name='rfc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='maestros',
            name='clave_maestro',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
