# Generated by Django 5.0.2 on 2025-10-17 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_movil_escolar_api', '0004_rename_especialidad_maestros_área_investigación_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maestros',
            name='edad',
        ),
    ]
