# Generated by Django 5.0.2 on 2025-10-17 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_movil_escolar_api', '0006_alumnos_fecha_nacimiento_maestros_cubículo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maestros',
            name='materias_json',
            field=models.TextField(blank=True, null=True),
        ),
    ]
