# Generated by Django 5.0.2 on 2025-10-17 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_movil_escolar_api', '0007_maestros_materias_json'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maestros',
            old_name='área_investigación',
            new_name='area_investigacion',
        ),
        migrations.RenameField(
            model_name='maestros',
            old_name='cubículo',
            new_name='cubiculo',
        ),
    ]
