# Generated by Django 5.0.2 on 2025-12-01 23:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_movil_escolar_api', '0008_rename_área_investigación_maestros_area_investigacion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventosAcademicos',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_evento', models.CharField(max_length=200)),
                ('tipo_evento', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_realizacion', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('lugar', models.CharField(max_length=200)),
                ('publico_objetivo', models.TextField(blank=True, null=True)),
                ('programa_educativo', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion', models.TextField(max_length=300)),
                ('cupo_maximo', models.IntegerField()),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
